name: CRIB
channels:
  - pytorch
  - conda-forge
  - dglteam/label/cu121
  - nvidia
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - anyqt=0.2.0
  - attrs=24.2.0
  - backcall=0.2.0
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - cairo=1.16.0
  - catboost=1.2.3
  - cccl=2.3.2
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - commonmark=0.9.1
  - contourpy=1.2.0
  - cuda-cccl=12.4.127
  - cuda-cccl_win-64=12.4.127
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-opencl-dev=12.4.127
  - cuda-profiler-api=12.4.127
  - cuda-runtime=12.1.0
  - cuda-version=12.4
  - cycler=0.11.0
  - decorator=5.1.1
  - dgl=2.0.0.cu121
  - dictdiffer=0.9.0
  - et_xmlfile=1.1.0
  - expat=2.6.4
  - fftw=3.3.9
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - future=1.0.0
  - getopt-win32=0.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmpy2=2.1.2
  - graphite2=1.3.14
  - graphviz=2.50.0
  - gts=0.7.6
  - harfbuzz=4.3.0
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - itsdangerous=2.2.0
  - jaraco.classes=3.2.1
  - jedi=0.19.2
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - keyrings.alt=5.0.0
  - khronos-opencl-icd-loader=2024.05.08
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.5.147
  - libcurand-dev=10.3.5.147
  - libcurl=8.9.1
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libgd=2.3.3
  - libglib=2.78.4
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libpng=1.6.39
  - libpq=17.2
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxgboost=2.1.1
  - libxml2=2.13.5
  - loguru=0.7.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.0.15
  - orange-canvas-core=0.1.35
  - orange-widget-base=4.22.0
  - orange3=3.36.2
  - packaging=24.1
  - pandas=1.5.3
  - pango=1.50.7
  - parso=0.8.4
  - patsy=0.5.6
  - pcre2=10.42
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.2
  - pixman=0.40.0
  - plotly=5.24.1
  - ply=3.11
  - poppler=24.09.0
  - poppler-data=0.4.11
  - psutil=5.9.0
  - pure_eval=0.2.2
  - py-xgboost=2.1.1
  - pybind11-abi=5
  - pyparsing=3.2.0
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.9.20
  - python-dateutil=2.9.0post0
  - python-graphviz=0.20.1
  - python_abi=3.9
  - pytorch=2.4.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qasync=0.27.1
  - qt-main=5.15.2
  - requests=2.32.3
  - scikit-learn=1.3.0
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - statsmodels=0.14.4
  - sympy=1.13.2
  - tbb=2021.8.0
  - tenacity=9.0.0
  - threadpoolctl=3.5.0
  - tomli=2.0.1
  - tornado=6.4.2
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzdata=2024b
  - ucrt=10.0.20348.0
  - ujson=5.10.0
  - unicodedata2=15.1.0
  - url-normalize=1.4.3
  - urllib3=2.2.3
  - vc=14.40
  - vs2015_runtime=14.42.34433
  - wheel=0.44.0
  - win32_setctime=1.1.0
  - win_inet_pton=1.1.0
  - xgboost=2.1.1
  - xlrd=2.0.1
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - anyio==3.7.1
      - asttokens==3.0.0
      - backports-tarfile==1.2.0
      - baycomp==1.0.3
      - cattrs==24.1.2
      - chardet==5.2.0
      - comm==0.2.2
      - debugpy==1.8.11
      - docutils==0.21.2
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - h11==0.12.0
      - httpcore==0.13.7
      - httpx==0.19.0
      - ipython==8.18.1
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - jupyter-client==8.6.3
      - keyring==25.5.0
      - keyrings-alt==5.0.2
      - matplotlib-inline==0.1.7
      - more-itertools==10.5.0
      - opentsne==1.0.2
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.48
      - pure-eval==0.2.3
      - pygments==2.18.0
      - pyqtgraph==0.13.7
      - pyqtwebengine==5.15.7
      - pyqtwebengine-qt5==5.15.2
      - python-louvain==0.16
      - pywin32==308
      - pywin32-ctypes==0.2.3
      - pyzmq==26.2.0
      - qtconsole==5.6.1
      - qtpy==2.4.2
      - requests-cache==1.2.1
      - rfc3986==1.5.0
      - serverfiles==0.3.1
      - sniffio==1.3.1
      - stack-data==0.6.3
      - torchaudio==2.4.1
      - torchvision==0.19.1
      - wcwidth==0.2.13
      - xlsxwriter==3.2.0
